Repository thomaspoignant/go-feature-flag, pull requests merged in 2021-06, with the labels that each got.

#167 (bug) Fix a problem in the exported data for the variation type
  feature_flag_test.go
  variation.go
  variation_test.go
Labels: bug

#168 introduce version field for the flags
  README.md
  docs/flag_format.md
  ffexporter/file_test.go
  ffexporter/webhook_test.go
  internal/exporter/data_exporter_test.go
  internal/exporter/feature_event.go
  internal/model/flag.go
  internal/model/flag_pub_test.go
  internal/model/variation_result.go
  internal/notifier/notifier_slack.go
  internal/notifier/notifier_slack_test.go
  testdata/benchmark/flag-config.yaml
  testdata/ffexporter/file/all_default.json
  testdata/ffexporter/file/custom_file_name.json
  testdata/ffexporter/s3/all_default.json
  testdata/ffexporter/webhook/valid_with_signature.json
  testdata/ffexporter/webhook/valid_without_signature.json
  testdata/internal/notifier/slack/should_call_webhook_and_have_valid_results.json
  variation.go
Labels: enhancement

#140 chore: rm PollInterval field
  config.go
  feature_flag.go
Labels: on-hold
