Repository thomaspoignant/go-feature-flag, pull requests merged in 2023-03, with the labels that each got.

#555 relay-proxy: Add metrics endpoint for prometheus
  cmd/metric/metrics.go
  cmd/relayproxy/api/server.go
  cmd/relayproxy/controller/all_flags.go
  cmd/relayproxy/controller/flag_eval.go
  cmd/relayproxy/controller/info.go
  cmd/relayproxy/docs/docs.go
  cmd/relayproxy/docs/swagger.json
  cmd/relayproxy/docs/swagger.yaml
  cmd/relayproxy/modeldocs/metricsController.go
  cmd/relayproxy/testdata/config/valid-file.yaml
  go.mod
  go.sum
  website/docs/relay_proxy/monitor_relay_proxy.md
Labels: relay-proxy

#560 Move metrics package to cmd/relayproxy
  cmd/relayproxy/api/server.go
  cmd/relayproxy/controller/all_flag_test.go
  cmd/relayproxy/controller/all_flags.go
  cmd/relayproxy/controller/flag_eval.go
  cmd/relayproxy/controller/flag_eval_test.go
  cmd/relayproxy/metric/metrics.go
Labels: automerge

#557 Allow multiple input files for configuration
  cmd/relayproxy/config/config.go
  cmd/relayproxy/service/gofeatureflag.go
  cmd/relayproxy/service/gofeatureflag_test.go
  config.go
  config_test.go
  examples/retriever_multiple_config_files/flags2.yaml
  examples/retriever_multiple_config_files/main.go
  feature_flag.go
  feature_flag_test.go
  internal/cache/cache_manager.go
  internal/cache/cache_manager_test.go
  testdata/flag-config-2nd-file.yaml
  testdata/multiple_files/config-1.yaml
  testdata/multiple_files/config-2.yaml
  testdata/multiple_files/flag-config.yaml
  variation_test.go
  website/blog/2023-03-17-multiple-config-file/index.mdx
  website/blog/2023-03-17-multiple-config-file/retriever-flow.png
  website/docs/configure_flag/store_your_flags.md
  website/docs/go_module/configuration.md
  website/docs/relay_proxy/configure_relay_proxy.md
Labels: enhancement

#571 Improve coverage
  .golangci.yml
  cmd/lint/linter_test.go
  cmd/migrationcli/main.go
  cmd/migrationcli/main_test.go
  cmd/relayproxy/config/config_test.go
  cmd/relayproxy/error/invalid_param.go
  cmd/relayproxy/log/logger_test.go
  cmd/relayproxy/metric/metrics_test.go
  cmd/relayproxy/modeldocs/metricsController.go
  cmd/relayproxy/service/gofeatureflag_test.go
  cmd/relayproxy/service/monitoring_test.go
  exporter/fileexporter/exporter.go
  exporter/logsexporter/exporter.go
  exporter/webhookexporter/exporter.go
  internal/utils/json_type_extractor_test.go
  retriever/fileretriever/retriever.go
  testutils/gc_storage_client_mock.go
  testutils/gc_storage_reader_mock.go
  testutils/httpclient_mock.go
  testutils/mock/exporter_mock.go
  testutils/mock/http_mock.go
  testutils/s3manager_mock.go
Labels: automerge

#595 Add integration test for the JS provider
  .github/dependabot.yml
  .github/workflows/ci.yml
  openfeature/provider_tests/.gitignore
  openfeature/provider_tests/integration_tests.sh
  openfeature/provider_tests/java-integration-tests/src/test/java/org/gofeatureflag/integrationtests/ProviderTests.java
  openfeature/provider_tests/js-integration-tests/package-lock.json
  openfeature/provider_tests/js-integration-tests/package.json
  openfeature/provider_tests/js-integration-tests/provider.test.js
Labels: automerge

#604 Push go-feature-flag relay proxy to homebrew
  .github/workflows/release.yml
  cmd/relayproxy/README.md
  website/docs/relay_proxy/install_relay_proxy.md
  website/versioned_docs/version-v1.6.0/relay_proxy/install_relay_proxy.md
Labels: automerge

#635 goreleaser fix warnings
  .github/workflows/release.yml
  .goreleaser.yaml
Labels: automerge

#611 Add provider tests for .NET
  .github/dependabot.yml
  .github/workflows/ci.yml
  openfeature/provider_tests/dotnet-integration-tests/.gitignore
  openfeature/provider_tests/dotnet-integration-tests/ProviderTests/ProviderTests.cs
  openfeature/provider_tests/dotnet-integration-tests/ProviderTests/ProviderTests.csproj
  openfeature/provider_tests/dotnet-integration-tests/ProviderTests/Usings.cs
  openfeature/provider_tests/dotnet-integration-tests/dotnet-integration-tests.sln
  openfeature/provider_tests/integration_tests.sh
Labels: automerge

#644 Add codecov token in the GHA
  .github/workflows/ci.yml
Labels: CI, automerge

#645 Add product pages in the website
  website/docusaurus.config.js
  website/src/pages/product/open_feature_support/index.mdx
  website/src/pages/product/styles.module.css
  website/src/pages/product/what_is_feature_management/index.mdx
  website/src/pages/product/what_is_feature_management/target.png
  website/src/pages/product/why_go_feature_flag/index.mdx
  website/static/img/features/rollout.png
Labels: automerge

#646 Website: Add developers section
  website/blog/2023-03-29-best_practice/best-practice.png
  website/blog/2023-03-29-best_practice/index.mdx
  website/blog/authors.yml
  website/docusaurus.config.js
  website/src/pages/product/open_feature_support/index.mdx
Labels: automerge
